platform :ios, ’13.0’
use_frameworks!

def install_pods
  pod 'SVProgressHUD'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'AlamofireImage'
end

target ’GitHub’ do
  install_pods
end

target 'GitHubTests' do
  install_pods
end

